# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
#gem "jekyll"
gem "github-pages"
gem "csv"
gem "base64"
gem "kramdown-parser-gfm"
gem "bigdecimal"

group :jekyll_plugins do
  gem "jekyll-sitemap"
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
end
